*** Variables ***
${ACCOUNTS_GITHUB_EMAIL}                   %{ACCOUNTS_GITHUB_EMAIL}
${ACCOUNTS_GITHUB_PASSWORD}                %{ACCOUNTS_GITHUB_PASSWORD}
${ACCOUNTS_GITHUB_USERNAME}                %{ACCOUNTS_GITHUB_USERNAME}

